# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java (Functional Tests For Failure Behaviors)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 26

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Test with Gradle and Verify Subset of Tests Passes
        run: ./gradlew testWithFaultInjectionShouldFails || ! grep -Fq "MustPass" /home/runner/work/filibuster-java-instrumentation/filibuster-java-instrumentation/build/reports/tests/testWithFaultInjectionShouldFails/index.html
